### ISSUE TITLE
centos导出PDF，报错“"Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.”

### ISSUE THREAD

**Issue by zhh2017** [dotnetcore/Magicodes.IE#404]
centos8环境，使用Magicodes.IE.Pdf2.6.4 导出PDF时，报错"Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported."

而使用Magicodes.IE.Excel2.6.4导出Excel功能正常。

#### package versions
Magicodes.IE.Excel 2.6.4, Magicodes.IE.Pdf 2.6.4

**Comment by xin-lai** [comment]
试试安装一下 `libgdiplus`呢？
可以参考一下：[Magicodes.IE在Docker中使用](https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/4.%E5%9C%A8Docker%E4%B8%AD%E4%BD%BF%E7%94%A8.md)

**Comment by zhh2017** [comment]
@xin-lai 谢谢。
检查系统环境了，已经安装libgdiplus ，字体库simsun.ttc也已经配置了。但是这个错误信息还是一直存在。
为了验证系统环境，使用itextsharp，是可以正常生成及导出PDF。
不知还有哪些排查的问题点？

**Comment by zhh2017** [comment]
![image](https://user-images.githubusercontent.com/34387161/166877706-973f836f-cf76-4c0c-89d8-6c8572aa7f5c.png)
直接使用wkhtmltopdf ，生成网页的pdf也没问题。

**Comment by hueifeng** [comment]
Maybe it's related to https://github.com/HakanL/WkHtmlToPdf-DotNet/issues/28

**Comment by hueifeng** [comment]
> Maybe it's related to [HakanL/WkHtmlToPdf-DotNet#28](https://github.com/HakanL/WkHtmlToPdf-DotNet/issues/28)

@zhh2017 按照该issue所说，是不是可以尝试安装“libjpeg62”？

**Comment by zhh2017** [comment]
找到问题原因，依赖项 libwkhtmltox.dll libwkhtmltox.dydll、libwkhtmltox.so，无法从系统环境中加载。
将依赖项文件放到发布后的runtimes中。问题解决。

**Comment by cicna** [comment]
Step 10/17 : RUN apt-get update && apt-get install -y fontconfig
 ---> Running in 6b5a76cce7b1
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [176 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2592 B]
Fetched 8569 kB in 5min 10s (27.6 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1 libfreetype6 libpng16-16
  sensible-utils ucf
The following NEW packages will be installed:
  fontconfig fontconfig-config fonts-dejavu-core libfontconfig1 libfreetype6
  libpng16-16 sensible-utils ucf
0 upgraded, 8 newly installed, 0 to remove and 3 not upgraded.
Need to get 2914 kB of archives.
After this operation, 6268 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 sensible-utils all 0.0.14 [14.8 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 ucf all 3.0043 [74.0 kB]
Get:3 http://deb.debian.org/debian bullseye/main amd64 libpng16-16 amd64 1.6.37-3 [294 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 libfreetype6 amd64 2.10.4+dfsg-1+deb11u1 [418 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 fonts-dejavu-core all 2.37-2 [1069 kB]
Get:6 http://deb.debian.org/debian bullseye/main amd64 fontconfig-config all 2.13.1-4.2 [281 kB]
Get:7 http://deb.debian.org/debian bullseye/main amd64 libfontconfig1 amd64 2.13.1-4.2 [347 kB]
Get:8 http://deb.debian.org/debian bullseye/main amd64 fontconfig amd64 2.13.1-4.2 [417 kB]
**debconf: delaying package configuration, since apt-utils is not installed**
Fetched 2914 kB in 1min 54s (25.6 kB/s)
Selecting previously unselected package sensible-utils.
(Reading database ... 10148 files and directories currently installed.)
Preparing to unpack .../0-sensible-utils_0.0.14_all.deb ...
Unpacking sensible-utils (0.0.14) ...
Selecting previously unselected package ucf.
Preparing to unpack .../1-ucf_3.0043_all.deb ...
Moving old data out of the way
Unpacking ucf (3.0043) ...
Selecting previously unselected package libpng16-16:amd64.
Preparing to unpack .../2-libpng16-16_1.6.37-3_amd64.deb ...
Unpacking libpng16-16:amd64 (1.6.37-3) ...
Selecting previously unselected package libfreetype6:amd64.
Preparing to unpack .../3-libfreetype6_2.10.4+dfsg-1+deb11u1_amd64.deb ...
Unpacking libfreetype6:amd64 (2.10.4+dfsg-1+deb11u1) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../4-fonts-dejavu-core_2.37-2_all.deb ...
Unpacking fonts-dejavu-core (2.37-2) ...
Selecting previously unselected package fontconfig-config.
Preparing to unpack .../5-fontconfig-config_2.13.1-4.2_all.deb ...
Unpacking fontconfig-config (2.13.1-4.2) ...
Selecting previously unselected package libfontconfig1:amd64.
Preparing to unpack .../6-libfontconfig1_2.13.1-4.2_amd64.deb ...
Unpacking libfontconfig1:amd64 (2.13.1-4.2) ...
Selecting previously unselected package fontconfig.
Preparing to unpack .../7-fontconfig_2.13.1-4.2_amd64.deb ...
Unpacking fontconfig (2.13.1-4.2) ...
Setting up libpng16-16:amd64 (1.6.37-3) ...
Setting up fonts-dejavu-core (2.37-2) ...
Setting up sensible-utils (0.0.14) ...
Setting up libfreetype6:amd64 (2.10.4+dfsg-1+deb11u1) ...
Setting up ucf (3.0043) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Setting up fontconfig-config (2.13.1-4.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Setting up libfontconfig1:amd64 (2.13.1-4.2) ...
Setting up fontconfig (2.13.1-4.2) ...
Regenerating fonts cache... done.
Processing triggers for libc-bin (2.31-13+deb11u3) ...
Removing intermediate container 6b5a76cce7b1
 ---> fb8b9329c3db
Step 11/17 : COPY /simsun.ttc /usr/share/fonts/simsun.ttc
COPY failed: file not found in build context or excluded by .dockerignore: stat simsun.ttc: file does not exist

**Comment by hueifeng** [comment]
@cicna 解压一下文件夹，将这个文件放过去，使Docker Copy时能找到改文件
[simsun.zip](https://github.com/dotnetcore/Magicodes.IE/files/9349760/simsun.zip)

**Comment by cicna** [comment]
`#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
#推荐大家使用此基础镜像（Asp.Net 6.0（包含字体））构建，理由见下文。该镜像通过海外构建已安装libgdiplus库。https://github.com/xin-lai/aspnetcore-docker
FROM ccr.ccs.tencentyun.com/magicodes/aspnetcore-runtime:6.0withfonts AS base

#FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src/src/Demo.Web
RUN dotnet restore -nowarn:msb3202,nu1503
RUN dotnet build --no-restore -c Release -o /app

FROM build AS publish
RUN dotnet publish --no-restore -c Release -o /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
		libjpeg62 \
		libjpeg62-turbo \
		libpng16-16 \
     && rm -rf /var/lib/apt/lists/*
# 从Demo.Web目录下复制字体文件（下载地址https://github.com/dotnetcore/Magicodes.IE/files/9349760/simsun.zip）
RUN ls
COPY simsun.ttc /usr/share/fonts/simsun.ttc

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Demo.Web.dll"]`

研究出来了，这样可以在centos7.6中的docker部署，导出pdf（含base64图片）
用的是Magicodes.IE.Pdf.Abp 2.6.4

**Comment by cicna** [comment]
1、如果不用这个镜像
FROM ccr.ccs.tencentyun.com/magicodes/aspnetcore-runtime:6.0withfonts AS base
，则报错误：

An unhandled exception has occurred while executing the request.
System.AggregateException: One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.)
 ---> System.NotSupportedException: Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.
 
 2、已有安装libjpeg62的命令，却还是报这个错误。请问是缺安装什么内容呢？
3、dockerfile文件内容：
`FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src/src/Demo.Web
RUN dotnet restore -nowarn:msb3202,nu1503
RUN dotnet build --no-restore -c Release -o /app


#安装fontconfig库，用于Pdf导出
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
		fontconfig \
		libjpeg62 \
		libjpeg62-turbo \
		libpng16-16 \
     && rm -rf /var/lib/apt/lists/*
#复制字体文件
RUN ls
COPY simsun.ttc /usr/share/fonts/simsun.ttc

FROM build AS publish
RUN dotnet publish --no-restore -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Demo.Web.dll"]`

**Comment by cicna** [comment]
1、如果不用这个镜像
FROM ccr.ccs.tencentyun.com/magicodes/aspnetcore-runtime:6.0withfonts AS base
，则报错误：

An unhandled exception has occurred while executing the request.
System.AggregateException: One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.)
 ---> System.NotSupportedException: Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.
 
 
2、已有安装libjpeg62的命令，却还是报这个错误。请问是缺安装什么内容呢？
3、dockerfile文件内容：
 
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src/src/Demo.Web
RUN dotnet restore -nowarn:msb3202,nu1503
RUN dotnet build --no-restore -c Release -o /app


#安装fontconfig库，用于Pdf导出
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
		fontconfig \
		libjpeg62 \
		libjpeg62-turbo \
		libpng16-16 \
     && rm -rf /var/lib/apt/lists/*
#复制字体文件
RUN ls
COPY simsun.ttc /usr/share/fonts/simsun.ttc

FROM build AS publish
RUN dotnet publish --no-restore -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Demo.Web.dll"]

**Comment by xiebiao360** [comment]
> 找到问题原因，依赖项 libwkhtmltox.dll libwkhtmltox.dydll、libwkhtmltox.so，无法从系统环境中加载。 将依赖项文件放到发布后的runtimes中。问题解决。[参照文件](https://github.com/HakanL/WkHtmlToPdf-DotNet/releases/tag/testapp)

谁知道 libwkhtmltox.dll libwkhtmltox.dydll、libwkhtmltox.so这几个文件是哪里来的呢？
